import { Geist, Geist_Mono } from "next/font/google";
import "./global.css";
import NavBar from "../components/NavBar";

// this page is similar to our page index.html

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <head>
        <link rel="stylesheet" href="/style/main.css"/>
      </head>
      <body>
        <NavBar title={"Our Social Media Platform"}/>
        {children}
        <NavBar/>
        </body>
    </html>
  );
}
